// User
export const REQUEST_CREATE_USER = 'REQUEST_CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// Current Document
export const REQUEST_CURRENT_DOCUMENT = 'REQUEST_CURRENT_DOCUMENT';
export const RECEIVE_CURRENT_DOCUMENT = 'RECEIVE_CURRENT_DOCUMENT';
export const UPDATE_CURRENT_DOCUMENT = 'UPDATE_CURRENT_DOCUMENT';
export const REMOVE_CURRENT_DOCUMENT = 'REMOVE_CURRENT_DOCUMENT';
export const DID_REMOVE_CURRENT_DOCUMENT = 'DID_REMOVE_CURRENT_DOCUMENT';
export const UPDATE_INDEX_CHECKPOINTS = 'UPDATE_INDEX_CHECKPOINTS';
export const SWITCH_CURRENT_DOCUMENT = 'SWITCH_CURRENT_DOCUMENT';

// Text Blocks
export const REQUEST_BLOCKS = 'REQUEST_BLOCKS';
export const RECEIVE_BLOCKS = 'RECEIVE_BLOCKS';
export const CLEAR_BLOCKS = 'CLEAR_BLOCKS';

// Bookshelf
export const REQUEST_BOOKSHELF_DOCUMENTS = 'REQUEST_BOOKSHELF_DOCUMENTS';
export const RECEIVE_BOOKSHELF_DOCUMENTS = 'REQUEST_BOOKSHELF_DOCUMENTS';
export const REMOVE_BOOKSHELF_DOCUMENT = 'REMOVE_BOOKSHELF_DOCUMENT';

// Library
export const REQUEST_LIBRARY_DOCUMENTS = 'REQUEST_LIBRARY_DOCUMENTS';
export const RECEIVE_LIBRARY_DOCUMENTS = 'RECEIVE_LIBRARY_DOCUMENTS';

// Modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';